### ISSUE TITLE
maru version not support in swagger

### ISSUE THREAD

**Issue by AndwareSsj** [falood/maru_swagger#11]
I make maru and maru_swagger use in phoenix have two issue:
1. version match
I config maru 

```
config :maru, PhoenixMaru.APIs.Homepage,
  versioning: [
    using: :path
  ]
```

the swagger request url not contains 'v1' param,like this:

```
curl -X GET --header 'Accept: text/html' 'http://localhost:4000/api/admin/users/6'
```

but correct is this
```
curl -X GET --header 'Accept: text/html' 'http://localhost:4000/api/v1/admin/users/6'
```
2.request body type

if request is post,put,delete and so on. the swagger params type will be body,not param line
like this:
![swagger_post](https://cloud.githubusercontent.com/assets/5350799/14271743/a49c563e-fb2e-11e5-9169-cbd6b129a6d6.png)
![swagger_put](https://cloud.githubusercontent.com/assets/5350799/14271750/aaa8b9aa-fb2e-11e5-9e1e-a3527138b3f5.png)

but get is well
like this:
![swagger_get_well](https://cloud.githubusercontent.com/assets/5350799/14271755/b8fe0942-fb2e-11e5-9b90-43b59bb93dad.png)

**Comment by falood** [comment]
`maru_swagger` haven't do it well this version, but you can custom it!
[here](https://github.com/falood/maru_examples/blob/63ce968550da40206ebcca8bb786d42c6c351904/phoenix_maru/web/apis/homepage.ex#L47-L77) is an example for using path based versioning with phoenix.

By the way, I plan to focus on compatible between `maru` and `phoenix` in next version of `maru`. Any idea, leave me a line please.

**Comment by AndwareSsj** [comment]
I set prefix: ["v1"] and basePath: "/api",it seem do well,but in my mind, this will be automatic like grape.
and the other issue. I read code from params_extractor.ex in module NonGetParamsGenerator function generator. I doesn't understand why you always set no get param to body and i replace this to:

Enum.map(param_list, fn ({key, value}) -> %{name: Atom.to_string(key), description: Map.get(value, :description), type: Map.get(value, :type), required: Map.get(value, :required), in: "formData"}  end)
it seems to be greater

**Comment by Cifer-Y** [comment]
@AndwareSsj 
Thank you for pointing out this.
well, I think that was my carelessness.
To be honest, I cannot remember why I wrote the code that way.
We'll fix the problem as soon as possible.
Anyway, if you have any good idea, a pull request is very welcome.

**Comment by falood** [comment]
1. `path` formatter depends on `maru` and I'll update maru for making it automatic like grape next version.
2. It seems that `formData` is better than `body`,I will probably make both available.

**Comment by falood** [comment]
@Cifer-Y `formData` doesn't support nested parameters, maybe that's the reason that we chose `body`.

**Comment by AndwareSsj** [comment]
I know this, but in my mind, we can make judgement, nested parameters or binary use body type, other use formData type.

**Comment by falood** [comment]
@AndwareSsj good idea :D deal
