### ISSUE TITLE
Document response status codes and schemas

### ISSUE THREAD

**Issue by mbuhot** [falood/maru_swagger#12]
maru_swagger provides a way to document the request params and schema, but I can't see a way to document the response HTTP status code (200, 201, 204, etc..) and response JSON body schema.
There could be a section similar to params that allows documenting the potential responses:

```
namespace :user do
  desc "Get User"
  params do
    requires :user_id, type: Integer
  end
  responses do
    status: 200, desc: "OK", type: :user
    status: 404, desc: "User not found"
  end
  get do
    ...
  end
end
```

**Comment by falood** [comment]
Just like my response here https://github.com/falood/maru/issues/22, I'll enhancement swagger support after maru v0.10 release. 
Thank you for your suggestion about DSL.
