### ISSUE TITLE
Error when mix deps.get 

### ISSUE THREAD

**Issue by edossantos** [falood/maru_swagger#3]
Looking up alternatives for conflicting requirements on maru
  Activated version: 0.7.1
  From maru_swagger v0.1.0: ~> 0.3.0
  From mix.exs: ~> 0.7
** (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies

**Comment by slashmili** [comment]
+1

**Comment by Cifer-Y** [comment]
Sorry for that, I didn't handle the version very well, so for a quick solution, you can use:
`{ :maru_swagger, git: "git@github.com:falood/maru_swagger.git"}`
thank you for this issue and your patience
@edossantos @slashmili

**Comment by falood** [comment]
`maru_swagger` doesn't support router extend now. I'll make is work and release new version as soon as possible!

**Comment by falood** [comment]
maru_swagger 0.5 released! 
check https://hex.pm/packages/maru_swagger please.
