### ISSUE TITLE
  version "v1", using: :accept_version_header

### ISSUE THREAD

**Issue by edossantos** [falood/maru_swagger#4]
The accept_vesion_header seems not to be working when I put it on my router..
** Sorry for bothering you **
== Compilation error on file web/api/api_router.ex ==
** (FunctionClauseError) no function clause matching in Maru.Builder.DSLs.version/2
    expanding macro: Maru.Builder.DSLs.version/2
    web/api/api_router.ex:3: App.Router.User (module)
    (elixir) lib/kernel/parallel_compiler.ex:97: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8

**Comment by falood** [comment]
Versioning should be set within `config :maru` since v0.5, check https://maru.readme.io/docs/versioning please!
