### ISSUE TITLE
"key nil not found" when requesting from endpoint

### ISSUE THREAD

**Issue by johnhamelink** [falood/maru_swagger#6]
Hey there, thanks for making this.

I'm trying to hook up maru_swagger with maru running inside a phoenix application. When I attempt to go to the Swagger endpoint, I get the following error:

```
[error] #PID<0.375.0> running TestMaruProject.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /api/swagger
** (exit) an exception was raised:
    ** (KeyError) key nil not found in: %{"v2" => [%Maru.Router.Endpoint{block: {:|>, [line: 6], [{:conn, [line: 6], nil}, {:json, [line: 7], [{:%{}, [line: 7], [hello: :world]}]}]}, desc: "Testing", helpers: [], method: "GET", param_context: [], path: ["testing"], version: "v2"}]}
        (elixir) lib/map.ex:150: Map.fetch!/2
        lib/maru_swagger.ex:27: MaruSwagger.generate/1
        lib/maru_swagger.ex:15: MaruSwagger.call/2
        (test_maru_project) web/api/api.ex:1: TestMaruProject.API.call/2
        (phoenix) lib/phoenix/router/route.ex:157: Phoenix.Router.Route.forward/4
        (test_maru_project) lib/phoenix/router.ex:255: TestMaruProject.Router.dispatch/2
        (test_maru_project) web/router.ex:1: TestMaruProject.Router.do_call/2
        (test_maru_project) lib/test_maru_project/endpoint.ex:1: TestMaruProject.Endpoint.phoenix_pipeline/1
        (test_maru_project) lib/plug/debugger.ex:92: TestMaruProject.Endpoint."call (overridable 3)"/2
        (test_maru_project) lib/phoenix/endpoint/render_errors.ex:34: TestMaruProject.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

It seems that the error is coming from the result of `Maru.Router.Path.lstrip(path_info, path)` on Line 12 of `maru_swagger.ex` is returning `{:ok, []}`. When `List.first` is ran on `[]`, it returns `nil`.

The code in question is here: https://gist.github.com/johnhamelink/37d93d5439d43bd28d51

**Comment by falood** [comment]
@johnhamelink 
I'm so sorry for replaying you so late. I've fixed it via master and there's an example for using `maru` and `maru_swagger` within phoenix. https://github.com/falood/maru_examples/blob/master/phoenix_maru/web/apis/homepage.ex
And don't forget to config `:maru` within `config.exs` like this: https://github.com/falood/maru_examples/blob/master/phoenix_maru/config/dev.exs#L44-L48
